### ISSUE TITLE
component roadmap

### ISSUE THREAD

**Issue by jameslaneconkling** [jameslaneconkling/yard#11]
- [x] area chart (bivariate and single)
- [x] scatter plot
- [ ] bar charts
  - [ ] grouped bar chart
  - [x] bar chart
  - [x] stacked bar chart
  - [ ] duel scale grouped bar chart
- [ ] brush
- [ ] graph network
- [ ] tree
- [ ] sankey
- [ ] map
- [ ] bullet charts
- [ ] box plot

- [ ] text annotations
- [ ] symbol annotations (circles, likely landing on a line chart, or custom)

meh
- [x] pie/donut
- [ ] radial
